<a href="https://colab.research.google.com/github/SimaliNaaz/PWSKILLS/blob/main/Numpyassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
import numpy as np
arr=np.arange(6)
print("Array:",arr)
print("Data Type:",arr.dtype)

Array: [0 1 2 3 4 5]
Data Type: int64


2.Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np
arr=np.array([1.5,2.6,3.7])
isfloat=arr.dtype==np.float64
print("Is the datatype is float or not?",isfloat)

Is the datatype is float or not? True


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [ ]:
import numpy as np
arr=np.array([1+2j,3+4j,5+6j],dtype=np.complex128)
print("Array:",arr)
print("Datatype:",arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Datatype: complex128


4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arrtofloat=np.asarray(arr,dtype=np.float32)
print("original array:",arr)
print("converted array:",arrtofloat)
print(arrtofloat.dtype)

original array: [1 2 3 4 5]
converted array: [1. 2. 3. 4. 5.]
float32


5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np
arr=np.array([1.2345678,2.3456890,3.45678901])
convertedarray=np.asarray(arr,dtype=np.float32)
print('original array:',arr)
print(arr.dtype)
print('converted array',convertedarray)
print(convertedarray.dtype)

original array: [1.2345678  2.345689   3.45678901]
float64
converted array [1.2345678 2.345689  3.456789 ]
float32


6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [ ]:
import numpy as np
elements=input("Enter elements seperated with spaces:")
elements_list=[float(x) for x in elements.split() ]
arr=np.array(elements_list)
shape=arr.shape
size=arr.size
datatype=arr.dtype
print("shape:",shape)
print("size:",size)
print("Datatype:",datatype)

Enter elements seperated with spaces:1 2 3 4 5
shape: (5,)
size: 5
Datatype: float64


7.. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [25]:
import numpy as np
def array_dimension(arr):
    dimension = arr.ndim
    return dimension
arr=np.random.randint(1,4,(3,3))
print(arr)
print(array_dimension(arr))

[[2 1 2]
 [3 3 3]
 [3 3 1]]
2


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
import numpy as np
def item_size_info():
  elements=input("Enter elements seperated by spaces:")
  elements_list=[float(x) for x in elements.split()]
  arr=np.array(elements_list)
  itemsizebytes=arr.itemsize
  totalsizebytes=arr.nbytes
  return itemsizebytes,totalsizebytes
itemsizebytes,totalsizebytes=item_size_info()
print("Item size byte",itemsizebytes)
print("Total size byte",totalsizebytes)

Enter elements seperated by spaces:1 2 3 4 5
Item size byte 8
Total size byte 40


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np
def array_strides(arr):
   return arr.strides
def inputarray():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    print("Enter elements of the array row-wise:")
    elements = []
    for i in range(rows):
        row_elements = input().split()
        elements.append(row_elements)
    return np.array(elements, dtype=float)
user_arr = inputarray()
strides = array_strides(user_arr)
print("Strides of the array:", strides)
#a "stride" refers to the number of bytes to step in each dimension when traversing the array.
 #Strides are used to describe the memory layout of the array and how elements are stored in memory.

Enter the number of rows: 3
Enter the number of columns: 3
Enter elements of the array row-wise:
1 2 3
4 5 6
7 8 9
Strides of the array: (24, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
import numpy as np
def shape_stride_relationship():
  rows=int(input("Enter the number of rows:"))
  cols=int(input7("Enter the number of cols:"))
  print("Enter elements of the array row-wise:")
  elements=[]
  for i in range(rows):
    row_elements=input().split()
    elements.append(row_elements)
  arr=np.array(elements,dtype=float)
  return arr.shape,arr.strides
shape,strides=shape_stride_relationship()
print("shape of the array:",shape)
print("strides of the array:",strides)


Enter the number of rows:3
Enter the number of cols:3
Enter elements of the array row-wise:
1 2 3
4 5 6
7 8 9
shape of the array: (3, 3)
strides of the array: (24, 8)


11- Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
import numpy as np
def create_zeros_array(n):
  return np.zeros(n)
n=int(input("Enter the number of elements:"))
zeros_array=create_zeros_array(n)
print("Arrays of zeroes:",zeros_array)

Enter the number of elements:5
Arrays of zeroes: [0. 0. 0. 0. 0.]


12- Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
import numpy as np
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))
rows=int(input("Enter the number of rows:"))
cols=int(input("Enter the number ofcols:"))
ones_matrix=create_ones_matrix(rows,cols)
print("2D Numpy array")
print(ones_matrix)

Enter the numberof rows:3
Enter the number ofcols:3
2D Numpy array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


13- Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
import numpy as np
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)
start=int(input("Enter the start value:"))
stop=int(input("Enter the stop value:"))
step=int(input("Enter the step value:"))
generate_array=generate_range_array(start,stop,step)
print("Generated array:",generate_array)


Enter the start value:1
Enter the stop value:10
Enter the step value:2
Generated array: [1 3 5 7 9]


14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
import numpy as np
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)
start=float(input("Enter the start value:"))
stop=float(input("Enter the stop value:"))
num=int(input("Enter the num value:"))
linear_space_array=generate_linear_space(start,stop,num)
print("Generated space array:",linear_space_array)


Enter the start value:1.0
Enter the stop value:5.0
Enter the num value:5
Generated space array: [1. 2. 3. 4. 5.]


15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
import numpy as np
def create_identity_matrix(n):
  return np.eye(n)
n=int(input("Enter the size of identity matrix:"))
identity_matrix=create_identity_matrix(n)
print("generated matrix")
print(identity_matrix)

Enter the size of identity matrix:3
generated matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


16.Write a function that takes a Python list and converts it into a NumPy array

In [ ]:
import numpy as np
def list_to_numpy_array(py_list):
    return np.array(py_list)
input_list = input("Enter the elements of the list separated by spaces: ").split()
input_list = [float(i) for i in input_list]
numpy_array = list_to_numpy_array(input_list)
print("Original  list:", input_list)
print("Converted Narray:", numpy_array)
print("Type of the original Python list:", type(input_list))
print("Type of the converted NumPy array:", type(numpy_array))


Enter the elements of the list separated by spaces: 1 2 3 4 5
Original  list: [1.0, 2.0, 3.0, 4.0, 5.0]
Converted Narray: [1. 2. 3. 4. 5.]
Type of the original Python list: <class 'list'>
Type of the converted NumPy array: <class 'numpy.ndarray'>


17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.


In [ ]:
import numpy as np
original_array=np.array([1,2,3,4,5])
view_array=original_array.view()
original_array[0]=10
print("original array:",original_array)
print("view_array:",view_array)
print("original array identity:",id(original_array))
print("view array identity:",id(view_array))
#he numpy.view method is used to create a new array object that shares the data of an existing array.
#It's useful when you want to perform operations or calculations on the data of the original array without modifying it.

original array: [10  2  3  4  5]
view_array: [10  2  3  4  5]
original array identity: 137876929817616
view array identity: 137876929388368


 18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [26]:
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
  arr=np.concatenate((arr1, arr2), axis=0)
  return arr
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(concatenate_arrays(arr1,arr2,axis=0))

[[1 2]
 [3 4]
 [5 6]]


19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [28]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[5, 8],
                 [4, 10]])
concatenated_array = np.concatenate((arr1, arr2), axis=1)
concatenated_array

array([[ 1,  2,  3,  5,  8],
       [ 4,  5,  6,  4, 10]])

20.Write a function that vertically stacks multiple NumPy arrays given as a list.




In [30]:
import numpy as np
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
print(stack_arrays_vertically([arr1,arr2,arr3]))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
import numpy as np
def create_integer_array(start,stop,step):
  return np.arange(start,stop+1,step,dtype=int)
start=int(input("Enter the start of the range:"))
stop=int(input("Enter the end of the range:"))
step=int(input("Enter the step size:"))
result=create_integer_array(start,stop,step)
print("Result array:",result)


Enter the start of the range:3
Enter the end of the range:15
Enter the step size:2
Result array: [ 3  5  7  9 11 13 15]


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
import numpy as np
def generate_array():
  return np.linspace(0,1,10)
result_array=generate_array()
print(result_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:
import numpy as np
def generate_array():
  return np.logspace(0,3,5)
result=generate_array()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [34]:
import pandas as pd
np.random.seed(42)  # For reproducibility
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
df

Column1  Column2  Column3
0       52       93       15
1       72       61       21
2       83       87       75
3       75       88      100
4       24        3       22

25.. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [35]:
def replace_negative_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)
df=replace_negative_with_zeros(df, 'A')
df=replace_negative_with_zeros(df,'B')
df

A  B
0  1  5
1  2  0
2  0  7
3  4  0
4  0  9

26. Access the 3rd element from the given NumPy array arr = np.array([10, 20, 30, 40, 50])


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
third_element=arr[2]
print(third_element)

30


27.Retrieve the element at index (1, 2) from the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
element=arr_2d[1,2]
print(element)

6


28.Using boolean indexing, extract elements greater than 5 from the given NumPy array arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
import numpy as np
arr=np.array([3,8,2,10,5,7])
result=arr[arr>5]
print(result)

[ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
result=arr[2:6]
print(result)

[3 4 5 6]


30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
result=arr_2d[0:2,1:3]
print(result)

[[2 3]
 [5 6]]


31..Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [37]:
def extract_elements_by_indices(arr_2D, indices):
    return arr_2D.ravel()[indices]
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([1, 4, 2, 5, 7])
extract_elements_by_indices(arr_2D, indices)

array([2, 5, 3, 6, 8])

32.. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
import numpy as np
def filter_greater_than_threshold(arr,threshold):
  filtered_array=arr[arr>threshold]
  return filtered_array
print("Enter elements:")
arr=np.array(list(map(float,input().split())))
threshold=float(input("Enter threshold value:"))
filtered_result=filter_greater_than_threshold(arr,threshold)
print("Filtered elements greather than",threshold,":",filtered_result)



Enter elements:
1 2 3 4 5
Enter threshold value:2
Filtered elements greather than 2.0 : [3. 4. 5.]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [41]:
import numpy as np
def extract_elements_3d(array, indices_dim1, indices_dim2, indices_dim3):
   indices = (indices_dim1, indices_dim2, indices_dim3)
   extracted_elements = array[indices]
   return extracted_elements
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])
extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)

array([ 2, 12])

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [42]:
import numpy as np
def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,12,32,64])
condition1 = arr > 3
condition2 = arr % 2 == 0
elements_satisfying_conditions(arr, condition1, condition2)

array([ 4,  6,  8, 12, 32, 64])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [43]:
import numpy as np
def extract_elements_2d(array, row_indices, col_indices):
  arr=array[row_indices, col_indices]
  return arr
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row_indices = np.array([0,1,2])
col_indices = np.array([1,2,0])
extract_elements_2d(arr_2d, row_indices, col_indices)

array([2, 6, 7])

36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
import numpy as np
print("enter 3x3 elements:")
elements=list(map(float,input().split()))
arr=np.array(elements).reshape(3,3)
result=arr+5
print("original array:")
print(arr)
print("after adding 5:")
print(result)

enter 3x3 elements:
1 2 3 4 5 6 7 8 9
original array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
after adding 5:
[[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]


 37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [44]:
import numpy as np
arr1=np.array([[1,2,3]])
arr2=np.array([[1,2,3,4],
               [4,5,6,7],
               [5,6,7,8]])
arr_multi=arr1.T *arr2
arr_multi

array([[ 1,  2,  3,  4],
       [ 8, 10, 12, 14],
       [15, 18, 21, 24]])

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [46]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
arr_add=arr1.T+arr2
arr_add

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:
import numpy as np
print("Enter elements of arr1:")
arr1_elements=list(map(float,input().split()))
print("Enter elements of arr2:")
arr2_elements=list(map(float,input().split()))
arr1=np.array(arr1_elements).reshape(3,1)
arr2=np.array(arr2_elements).reshape(1,3)
result=arr1+arr2
print(result)

Enter elements of arr1:
1 2 3
Enter elements of arr2:
4 5 6
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


 40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [47]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 4],
                 [4, 6]])
arr2_reshaped = arr2[:,:, np.newaxis]
arr_multi=arr2*arr2_reshaped
arr_multi

array([[[ 1,  4],
        [16, 24]],

       [[ 4, 16],
        [24, 36]]])

41.Calculate column wise mean for the given array:arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
col_mean=np.mean(arr,axis=0)
print("column wise mean:",col_mean)

column wise mean: [2.5 3.5 4.5]


 42.Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
row_max=np.max(arr,axis=1)
print("maximum value:",row_max)

maximum value: [3 6]


43.. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
row_max=np.argmax(arr,axis=0)
print("indices of each column:",row_max)

indices of each column: [1 1 1]


44.. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_max1=np.cumsum(arr,axis=0)
arr_max1

array([[1, 2, 3],
       [5, 7, 9]])

 45.In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
columns=np.all(arr%2==0,axis=0)
print("are all elements are even?")
print(columns)

are all elements are even?
[False False False]


46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
original_array=np.array([1,2,3,4,5,6])
m=int(input("Enter the no of rows(m):"))
n=int(input("Enter the no of columns(n):"))
if m*n==original_array.size:
  reshapematrix=original_array.reshape(m,n)
  print("reshape matrix:")
  print(reshapematrix)
else:
  print("The product of m and n must be equal to size of array.")


Enter the no of rows(m):2
Enter the no of columns(n):3
reshape matrix:
[[1 2 3]
 [4 5 6]]


47.Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
def flatten_matrix(input_matrix):
  flattened_array=input_matrix.flatten()
  return flattened_array
input_matrix=np.array([[1,2,3],[4,5,6]])
flattened_array=flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


48.Write a function that concatenates two given arrays along a specified axis.array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [51]:
import numpy as np
def concatenate_arrays(array1, array2, axis):
  arr=np.concatenate((array1, array2), axis=axis)
  return arr
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenate_arrays(array1, array2, axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

49.Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
import numpy as np
def splitarray(original_array,axis,num_splits):
  return np.array_split(original_array,num_splits,axis=axis)
original_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")
print(original_array)
axis=int(input("Enter axis(either 0 or 1):"))
num_splits=int(input("Enter the number of splits:"))
splitarrays=splitarray(original_array,axis=axis,num_splits=num_splits)
print("Split arrays:")
for array in splitarrays:
  print(array)






Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Enter axis(either 0 or 1):1
Enter the number of splits:3
Split arrays:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]

In [ ]:
import numpy as np
def modify_array(original_array,indices_to_insert,values_to_insert,indices_to_delete):
  modified_array=np.insert(original_array,indices_to_insert,values_to_insert)
  modified_array=np.delete(modified_array,indices_to_delete)
  return modified_array
original_array=np.array([1,2,3,4,5])
indices_to_insert=[2,4]
values_to_insert=[10,11]
indices_to_delete=[1,3]
result_array=modify_array(original_array,indices_to_insert,values_to_insert,indices_to_delete)
print("Resultant array:",result_array)


Resultant array: [ 1 10  4 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
import numpy as np
arr1=np.random.randint(0,10,size=10)
arr2=np.arange(1,11)
result_array=arr1+arr2
print("Array arr1:",arr1)
print("Array arr2:",arr2)
print("Resultant array",result_array)

Array arr1: [5 5 0 5 9 1 6 2 7 9]
Array arr2: [ 1  2  3  4  5  6  7  8  9 10]
Resultant array [ 6  7  3  9 14  7 13 10 16 19]


52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
import numpy as np
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
result_array=arr1-arr2
print("Array arr1",arr1)
print("Array arr2",arr2)
print("Resultant array:",result_array)

Array arr1 [10  9  8  7  6  5  4  3  2  1]
Array arr2 [ 1  2  3  4  5  6  7  8  9 10]
Resultant array: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
import numpy as np
arr1=np.random.randint(0,10,size=5)
arr2=np.arange(1,6)
result_array=arr1*arr2
print("Array arr1",arr1)
print("Array arr2",arr2)
print("Resultant array:",result_array)

Array arr1 [9 6 7 4 0]
Array arr2 [1 2 3 4 5]
Resultant array: [ 9 12 21 16  0]


54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
import numpy as np
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
result_array=arr1/arr2
print("Array arr1:",arr1)
print("Array arr2:",arr2)
print("Resultant array:",result_array)

Array arr1: [ 2  4  6  8 10]
Array arr2: [1 2 3 4 5]
Resultant array: [2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
import numpy as np
arr1=np.arange(1,6)
arr2=arr1[::-1]
resultarray=np.power(arr1,arr2)
print("Array arr1:",arr1)
print("Array arr2:",arr2)
print("Resultant array:",resultarray)

Array arr1: [1 2 3 4 5]
Array arr2: [5 4 3 2 1]
Resultant array: [ 1 16 27 16  5]


56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
import numpy as np
def count_substring_occurences(arr,substring):
  count=0
  for string in arr:
    count +=string.count(substring)
  return count
arr=np.array(['hello','world','hello','numpy','hello'])
substring='hello'
occurences=count_substring_occurences(arr,substring)
print("occurences of '{}' in the array: {}".format(substring,occurences))


occurences of 'hello' in the array: 3


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np
def extract_uppercase_characters(arr):
  uppercase_chars=''
  for string in arr:
    for char in string:
      if char.isupper():
        uppercase_chars+=char
  return uppercase_chars
arr=np.array(["Hello","World","OpenAI",'GPT'])
uppercase_chars=extract_uppercase_characters(arr)
print("Uppercase characters:",uppercase_chars)

Uppercase characters: HWOAIGPT


58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as np
def replace_substring(arr,old_substring,new_substring):
  return np.char.replace(arr,old_substring,new_substring)
arr=np.array(['apple','banana','grape','pineapple'])
old_substring='apple'
new_substring='orange'
result_array=replace_substring(arr,old_substring,new_substring)
print("original array",arr)
print("Resultant array",result_array)

original array ['apple' 'banana' 'grape' 'pineapple']
Resultant array ['orange' 'banana' 'grape' 'pineorange']


59.. Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
import numpy as np
def concatenate_strings(arr1,arr2):
  return np.char.add(arr1,arr2)
arr1=np.array(['Hello','World'])
arr2=np.array(['open','AI'])
resultarray=concatenate_strings(arr1,arr2)
print("Array arr1:",arr1)
print("Array arr2:",arr2)
print("Result array:",resultarray)

Array arr1: ['Hello' 'World']
Array arr2: ['open' 'AI']
Result array: ['Helloopen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])





In [ ]:
import numpy as np
def longest_string(arr):
  string_length=np.vectorize(len)(arr)
  return np.max(string_length)
arr=np.array(['apple','banana','grape','pineapple'])
longestlength=longest_string(arr)
print("Length of longest string:",longestlength)


Length of longest string: 9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions

In [1]:
import numpy as np
np.random.seed(42)
dataset=np.random.randint(1,1001,size=100)
mean=np.mean(dataset)
median=np.median(dataset)
variance=np.var(dataset)
std_deviation=np.std(dataset)
print("Mean:",mean)
print("Median:",median)
print('Variance:',variance)
print("Standard Deviation:",std_deviation)


Mean: 474.79
Median: 463.5
Variance: 81245.46590000001
Standard Deviation: 285.0359028262931


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [ ]:
import numpy as np
def calculate_percentile():
  random_number=np.random.randint(1,101,size=50)
  print(f"Generated array of random numbers:{random_number}")
  percentile_25=np.percentile(random_number,25)
  percentile_75=np.percentile(random_number,75)
  print(f"25th percentile:{percentile_25}")
  print(f"75th percentile:{percentile_75}")
calculate_percentile()

Generated array of random numbers:[ 45  77  26  73  68  73   4  16  85  38   7  92 100  55   4  51  72  74
  64  51  42  99  53  59  70  18   8  89  57  88  56  11  76  45  94  53
  72  59  76  81  70  34  92  35  82  24  26  16  58  38]
25th percentile:35.75
75th percentile:75.5


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,4,6,8,10])
correlation_matrix=np.corrcoef(arr1,arr2)
correlation_coeffecient=correlation_matrix[0,1]
print(correlation_coeffecient)

0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.




In [ ]:
import numpy as np
matrix1=np.array([[1,2,3],[4,5,6]])
matrix2=np.array([[7,8],[9,10],[11,12]])
result=np.dot(matrix1,matrix2)
print(result)


[[ 58  64]
 [139 154]]


65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [1]:
import numpy as np
data=np.random.randint(10,1001,size=50)
percentiles=np.percentile(data,[10,25,50,75,90])
print("10th percentile:",percentiles[0])
print("25th percentile(Q1):",percentiles[1])
print("Median(50th percentile):",percentiles[2])
print("75th percentile:",percentiles[3])
print("90th percentile:",percentiles[4])

10th percentile: 147.2
25th percentile(Q1): 246.5
Median(50th percentile): 483.5
75th percentile: 746.0
90th percentile: 858.6


66. Create a NumPy array of integers and find the index of a specific element

In [53]:
import numpy as np
arr=np.array([1,2,3,4,5])
element_to_find = 5
index = np.where(arr == element_to_find)[0]
print("Index of", element_to_find, ":", index)

Index of 5 : [4]


67. Generate a random NumPy array and sort it in ascending order

In [ ]:
import numpy as np
random_array=np.random.randint(1,101,size=10)
sorted_array=np.sort(random_array)
print("Random array:",random_array)
print("sorted_array:",sorted_array)

Random array: [18 74 49 19 79  2 60  6 76 29]
sorted_array: [ 2  6 18 19 29 49 60 74 76 79]


68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [2]:
import numpy as np
arr=np.array([(12,25,6,42,8,30)])
filteredarray=arr[arr>20]
print(filteredarray)

[25 42 30]


69.Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [3]:
import numpy as np
arr=np.array([1,5,8,12,15])
filteredarray=arr[arr%3==0]
print(filteredarray)

[12 15]


70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [4]:
import numpy as np
arr=np.array([10,20,30,40,50])
filteredarray=arr[(arr>=20) & (arr<=40)]
print(filteredarray)

[20 30 40]


71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

In [58]:
import numpy as np
arr = np.array([1, 2, 3])
arr_4=np.byte(arr)
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


72.For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)


In [59]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.byteswap(True)
arr1

array([16777216, 33554432, 50331648], dtype=int32)

73.For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [60]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.newbyteorder()
arr1

array([16777216, 33554432, 50331648], dtype='>i4')

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

In [61]:
import numpy as np
rr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.byteswap(True)
arr2=arr.newbyteorder()
arr2

array([1, 2, 3], dtype='>i4')

75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.arr = np.array([1, 2, 3], dtype=np.int32)

In [62]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.dtype.byteorder
arr1

'='

76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [5]:
import numpy as np
arr1=np.arange(1,11)
copy_arr=arr1.copy()
copy_arr[0]=100
print("Original array:")
print(arr1)
print("Modified array:")
print(copy_arr)
if np.array_equal(arr1,copy_arr):
  print("Yes,Modifying arr1 affects copy_arr")
else:
  print("No,Modifying arr1 doesnot affect copy_arr")

Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Modified array:
[100   2   3   4   5   6   7   8   9  10]
No,Modifying arr1 doesnot affect copy_arr


77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [7]:
import numpy as np
matrix=np.random.randint(1,10,(3,3))
print("Original matrix:")
print(matrix)
view_slice=matrix[1:,1:]
print("View_Slice:")
print(view_slice)
view_slice[0,0]=100
print("Modified view_slice:")
print(matrix)



Original matrix:
[[6 5 8]
 [5 7 4]
 [5 1 7]]
View_Slice:
[[7 4]
 [1 7]]
Modified view_slice:
[[  6   5   8]
 [  5 100   4]
 [  5   1   7]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [8]:
import numpy as np
array_a=np.arange(1,13).reshape(4,3)
print("Original array:")
print(array_a)
view_b=array_a[1:3,1:3]
print("View_b")
print(view_b)
view_b+=5
print("Modified view_b:")
print(view_b)
print("Original array after modification:")
print(array_a)

Original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View_b
[[5 6]
 [8 9]]
Modified view_b:
[[10 11]
 [13 14]]
Original array after modification:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [11]:
import numpy as np
orig_array=np.arange(1,9).reshape(2,4)
print("Original array:")
print(orig_array)
reshaped_view=orig_array.reshape(4,2)
print("reshaped view:")
print(reshaped_view)
reshaped_view[0,0]=100
print("Modified reshaped view:")
print(reshaped_view)
print("original array:")
print(orig_array)

Original array:
[[1 2 3 4]
 [5 6 7 8]]
reshaped view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified reshaped view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]
original array:
[[100   2   3   4]
 [  5   6   7   8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [12]:
import numpy as np
data=np.random.randint(1,10,size=(3,4))
print("original data:")
print(data)
data_copy=np.copy(data[data>5])
print("copy data elements greater than 5:")
print(data_copy)
if data_copy.size>0:
  data_copy[0]=100
print("Modified data:")
print(data_copy)
print("original data after modification check:")
print(data)


original data:
[[4 9 4 7]
 [4 4 6 6]
 [3 2 6 1]]
copy data elements greater than 5:
[9 7 6 6 6]
Modified data:
[100   7   6   6   6]
original data after modification check:
[[4 9 4 7]
 [4 4 6 6]
 [3 2 6 1]]


81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [13]:
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array(([11,12,13,14],[15,16,17,18],[19,20,21,22]))
print("Matrix A:")
print(A)
print('Matrix B:')
print(B)
addition_result=A+B
print("Addition result:")
print(addition_result)
subtraction_result=A-B
print("Subtraction result:")
print(subtraction_result)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix B:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Addition result:
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Subtraction result:
[[-10 -10 -10 -10]
 [-10 -10 -10 -10]
 [-10 -10 -10 -10]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [16]:
import numpy as np
c=np.array([[1,2],[3,4],[5,6]])
d=np.array([[1,2,3,4],[5,6,7,8]])
print("Matrix C:")
print(c)
print("Matrix D:")
print(d)
result=c@d
print("result:")
print(result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]
Matrix D:
[[1 2 3 4]
 [5 6 7 8]]
result:
[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


83.Create a matrix `E` and find its transpose.

In [17]:
import numpy as np
E=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix E:")
print(E)
E_transpose=np.transpose(E)
print("Transpose:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


84.Generate a square matrix `F` and compute its determinant.

In [20]:
import numpy as np
F=np.array([[4,2,3],[3,5,7],[8,1,6]])
print("Matrix F:")
print(F)
determinant=np.linalg.det(F)
print("determinant:")
print(determinant)

Matrix F:
[[4 2 3]
 [3 5 7]
 [8 1 6]]
determinant:
57.00000000000001


85.Create a square matrix `G` and find its inverse.

In [57]:
import numpy as np
arr=np.random.randint(1,10,(3,3))
arr_inv = np.linalg.inv(arr)
arr_inv

array([[-0.10526316,  0.26315789, -0.05263158],
       [-0.42982456,  0.3245614 ,  0.20175439],
       [ 0.29824561, -0.24561404, -0.01754386]])